# Generated by Django 5.2.7 on 2026-02-07 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0010_add_task_start_date_and_update_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('catalog_type', models.CharField(choices=[('COURSE', 'course'), ('ROUTINE', 'routine'), ('WORK', 'work')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('work_date', models.DateField()),
                ('planned_hours', models.IntegerField()),
                ('spending_hours', models.IntegerField()),
                ('started_working_hours', models.TimeField()),
                ('ending_working_hours', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('description', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.AddField(
            model_name='projects',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_activities', to='schedular.projects'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='schedular.task'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
