# Generated by Django 5.2.7 on 2026-02-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0011_catalog_pending_remove_course_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending',
            name='Daily_task_id',
        ),
        migrations.DeleteModel(
            name='Daily_Activity',
        ),
    ]
