# Generated by Django 5.2.7 on 2026-02-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0011_catalog_dailyactivity_remove_course_instructor_and_more'),
        ('schedular', '0012_remove_pending_daily_task_id_delete_daily_activity'),
    ]

    operations = [
    ]
