# Generated by Django 5.2.7 on 2026-02-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0019_alter_catalog_estimated_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='progress_weight',
            field=models.IntegerField(default=0, help_text='Weight of this subtask in percentage - automatically calculated'),
        ),
    ]
